### ISSUE TITLE
Member access level not updated on transfer

### ISSUE THREAD

**Issue by deepsidhu85** [phac-nml/irida-next#226]
## Problem

When a user is a member in Group A as a `Maintainer`, and the user is a member of `Group B` as a `Guest` and then `Group B` is transferred into the `Group A` namespace, the member roles are not updated correctly and the user is left with `Maintainer` access in `Group A` and `Guest` access in `Group B`. This should not be happening as the access level should propagate into descendants starting at the parent

![image](https://github.com/phac-nml/irida-next/assets/25466211/3eadf969-8ff2-4a04-af77-60d31a200901)

![image](https://github.com/phac-nml/irida-next/assets/25466211/9020a085-ac4f-4b94-be5a-0e0234bff4e2)

**Note this issue also applies to a project transfer**

**To verify:**

Create 2 groups Group A and Group B, add `user2@email.com` as a `Maintainer` on Group A, add `user2@email.com` as a `Guest` on `Group B`. Now transfer `Group B` so that it's parent is `Group A`.  Visit the members page of `Group A` and you should see `user2@email.com` as a `Maintainer`. Now visit the members page of `Group B` and you should see `user2@email.com` as a `Guest`

## Solution

In the transfer service for groups and projects, if and only if the group has successfully been transferred to a new parent, we want to get the `Member` relationships for the new parent and it's ancestors. For each one of these member relationships we want go through the descendants of the new parent and update the memberships so that the access level is ascending through the descendants. This should ensure that at no point is the access level higher in an ancestor membership than it is in a descendant membership

**Couple of suggestions:**

1) To get the namespace and ancestor member relationships we can user the `Member.for_namespace_and_ancestors` scope which will accept a project namespace or group

2) To get the descendant relationships we can use `namespace.self_and_descendants`

3) We should most likely be able to use the `update_descendant_memberships` method in the `member` model to update descendant memberships for a user

4) We will probably want to set this up as a job that fires off once the parent has been updated and runs in the background as there could be a very large number of members

5) Break this issue up into smaller pieces ie; updating of group transfer memberships, updating of project transfer memberships, setting up job to update descendant memberships

## Acceptance criteria

After transferring a group or project under a new parent where the user was a member in the previous parent or it's ancestors, and is also a member in the new parent or it's ancestors, any membership for the user in the parent and it's descendants should be in descending order ie; the membership access level in a subgroup or project should be equal to or greater than the highest access level in the parent or it's ancestors

**Comment by ksierks** [comment]
Fixed.
