### ISSUE TITLE
Attachments: Update viewing attachments listing

### ISSUE THREAD

**Issue by joshsadam** [phac-nml/irida-next#232]
### Summary

Currently, the attachments page only displays the file name, size, uploaded date, and the ability to delete the attachment.  Extra metadata columns need to be added so that the user can see:

1.  Paired-end files should be displayed together, with their direction.
2.  File format
3.  File type (which platform was used to create it)

![](https://github.com/phac-nml/irida-next/assets/11295750/5ae9de95-7b77-469a-a5e8-6d60bc62ae99)

### Acceptance criteria

The user should easily be able to see these new metadata fields.  Colour coding them will allow users to distinguish similar file types and formats easily.

**Comment by ChrisHuynh333** [comment]
Clarification question: How would we determine which files are paired-end, and their respective directions?

**Comment by ericenns** [comment]
> Clarification question: How would we determine which files are paired-end, and their respective directions?

That support was added in PR #203 if you look at the tests and the service you can see how that is determined and saved to the models.
