### ISSUE TITLE
Workflow: DB Representation

### ISSUE THREAD

**Issue by ericenns** [phac-nml/irida-next#245]
## Summary
Since we are using the WES (Workflow Execution Service) that follows the GA4GH WES 1.1.0 standard (https://ga4gh.github.io/workflow-execution-service-schemas/docs/), to execute Pipelines we need to represent a Workflow Execution and its associated Samples in our database.

## Solution
* Create a `WorkflowExecution` model that has the following attributes
  * `workflow_params` type: `jsonb`
  * `workflow_type` type: `string`
  * `workflow_type_version` type: `string`
  * `tags` type: `string` (tbd)
  * `workflow_engine` type: `string`
  * `workflow_engine_version` type: `string`
  * `workflow_engine_parameters` type:  `string`
  * `workflow_url` type: `string`
  * `run_id` type: `string`
  * `submitter_id` type: `bigint` this points to `User` model
  * `state` type: `string` with accepted values of TBD

* Create a `SamplesWorkflowExecution` join model that has the following attributes
  * belongs_to :workflow_execution
  * belongs_to :sample
  * `samplesheet_params` type: `jsonb`

**Comment by JeffreyThiessen** [comment]
the `WorkflowExecution` model should include `workflow_engine_version` -> `string` and `workflow_attachment` -> `Array of strings <binary>` as attributes.

The attachments do not have an exact standard as of yet, so as they are right now it's just a array of strings. Maybe this should be left out of the first DB representation or included as a reference to another table/table entry that has lists of files.

**Comment by ericenns** [comment]
From our discussion lets add a `metadata` column that we will store `worfklow_name` and `workflow_version`.
