### ISSUE TITLE
Workflow: Deletion Service

### ISSUE THREAD

**Issue by ericenns** [phac-nml/irida-next#249]
## Summary
After a `WorfklowExecution` has either completed or errored, a user may want to delete it. Since this doesn't require a call to the WES API we can just delete immediately after the user clicks the `Delete` button for a workflow

## Acceptance Criteria
* Create a `WorkflowExecutions::DeletionService`
  * Accept a `workflow_execution` as parameters
  * Validate that the `workflow_execution` is in one of the `deletable` states (either completed, or errored)
  * If it is in one of the above states, then the workflow and it's children should be destroyed
  * A controller under workflow_executions
  * UI updated to include `Delete` on the workflow executions table listing

**Comment by ksierks** [comment]
@ericenns @deepsidhu85 @joshsadam Can I assume the workflow executions table will not have pagination, like the personal access token table? I'm trying to decide how best to remove the deleted worfkflow from the table. Thanks.

**Comment by ericenns** [comment]
@ksierks The workflow executions table will eventually have pagination, so I wouldn't take the same approach as the personal access tokens table.

**Comment by ksierks** [comment]
Currently, I am not required to implement action policies for this issue. Assume the user is the submitter.
