### ISSUE TITLE
Workflow: Submission UI

### ISSUE THREAD

**Issue by ericenns** [phac-nml/irida-next#256]
### Problem

As a user, I want to be able to create a workflow submission.

### Solution

1.  From any project a user has permission on, they should be able to select samples using checkboxes (exists).
2.  There needs to be a button to begin the submission process (disabled if no samples are selected?)
3.  When the button is clicked, it should open a modal displaying the ability to select which workflow to run.
4.  Once the workflow is selected, the next step is the workflow properties form (e.g. `nextflow_component`)
5.  Next, the form for sample confirmation based on the selected pipeline.

### Possible flow:

![](https://github.com/phac-nml/irida-next/assets/11295750/a4d79bba-8bcf-4cc2-a09b-9792ef221008)

**Comment by joshsadam** [comment]
Added in #313

**Comment by joshsadam** [comment]
Added in #313
