### ISSUE TITLE
Project Sample Metadata - Metadata sort: back-end

### ISSUE THREAD

**Issue by deepsidhu85** [phac-nml/irida-next#272]
## Summary
As a user I want to be able to sort the project samples and group samples table via a metadata column

## Acceptance Criteria
Add a custom sort method to the group and project_namespace models (`self.metadata_sort`) which will accept the field and direction as parameters
Sort at the group samples level should work on metadata fields
Sort at the project samples level should work on metadata fields

Note: The field and direction parameters are available in the controller via ransack

**Comment by ksierks** [comment]
My understanding is, this issue is also on hold, like #271.

**Comment by deepsidhu85** [comment]
Merged into #277
