### ISSUE TITLE
Workflow: workflow execution states

### ISSUE THREAD

**Issue by JeffreyThiessen** [phac-nml/irida-next#318]
### Summary

Workflow execution states have yet to be defined.

Once they are defined they should be added to the `workflow_executions` table as `enum`

Related to #245 

### Solution
Create a migration that changes the `state` column on `workflow_executions` to an enum.
Define an enum with defined states

Example code:
```
class AddWorkflowExecutionStates < ActiveRecord::Migration[7.0]
  def change
    create_enum :workflow_execution_state, ['some', 'states', 'go', 'here']
    change_column :workflow_executions, :state, :enum, enum_type: :workflow_execution_state
  end
end
```

**Comment by ericenns** [comment]
Superseded by #558
