### ISSUE TITLE
Paired Read detection limitation

### ISSUE THREAD

**Issue by jrober84** [phac-nml/irida-next#344]
When uploading paired reads to IRIDA next the program will only correctly pair read files which end with *_1.fastq{.gz} and *_2.fastq{.gz}. Reads are also frequently named with the convention *_R1.fastq{.gz} and *_R2.fastq{.gz}. Currently, the system treats these as individual read sets instead of a pair.  I have included a set of reads which can be used to reproduce this issue.

[A_R1.fastq.gz](https://github.com/phac-nml/irida-next/files/13745105/A_R1.fastq.gz)
[A_R2.fastq.gz](https://github.com/phac-nml/irida-next/files/13745107/A_R2.fastq.gz)

**Comment by JeffreyThiessen** [comment]
From my work on the irida uploader, these are all the common and uncommon formats
```
file_1.fastq(.gz)
file_2.fastq(.gz)
seq_R1.fastq(.gz)
seq_R2.fastq(.gz)
samp_F.fastq(.gz)
samp_R.fastq(.gz)
germ_f.fastq(.gz)
germ_r.fastq(.gz)
```

A rare version that sometimes happens is all of the above but delimited with `-` instead of `_`. In these cases I would usually just tell the user to format with a standard `_` ending.

**Comment by JeffreyThiessen** [comment]
A more thorough breakdown of pairing sequence data.

The following lines can be added to the test text at https://regexr.com
```
#simple cases
mysampname_mysampid_R1.fastq.gz
mysampname_R1.fastq.gz
mysampname_a_F.fastq.gz

mysampname_R.fastq.gz
mysampname_R.fastq

mysampname_mysampid_R1_001.fastq.gz
mysampname_mysampid_R2_001.fastq.gz

mysampname_mysampid_R1_002.fastq.gz
mysampname_mysampid_R2_002.fastq.gz

#exhaustive sets
file_1.fastq.gz
file_2.fastq.gz
seq_R1.fastq.gz
seq_R2.fastq.gz
samp_F.fastq.gz
samp_R.fastq.gz
germ_f.fastq.gz
germ_r.fastq.gz

file_1_001.fastq.gz
file_2_001.fastq.gz
seq_R1_001.fastq.gz
seq_R2_001.fastq.gz
samp_F_001.fastq.gz
samp_R_001.fastq.gz
germ_f_001.fastq.gz
germ_r_001.fastq.gz

file_1.fastq
file_2.fastq
seq_R1.fastq
seq_R2.fastq
samp_F.fastq
samp_R.fastq
germ_f.fastq
germ_r.fastq

##paired sets with special rules

# Each of theses should not match as they use different paired indicators
samp_F.fastq.gz
samp_r.fastq.gz
germ_f.fastq.gz
germ_R.fastq.gz
seq_R1.fastq
seq_2.fastq
file_R1.fastq
file_F.fastq

# These should not pair together
mysampname_mysampid_R1_001.fastq.gz
mysampname_mysampid_R2_002.fastq.gz

# These should not pair together
mysampname_mysampid_R1_002.fastq.gz
mysampname_mysampid_R2_001.fastq.gz

# These should not pair together
mysampname_mysampid_R1_002.fastq.gz
mysampname_mysampid_R2_001.fastq.gz

# unzipped and zipped should not pair together
file_1_001.fastq.gz
file_2_001.fastq
```
The above examples should all match as valid names individually, but will need more specific rules for matching them together as it is possible for samples with different seq run count id's or different direction indicators to be processed on the same samples.

This regex will match each individually, with text groups, when the `global` and `multiline` flags are set on https://regexr.com
```
^(?<SampleNameAndSometimesID>.*_)+(?<FowardReverseIndicator>R?[1-2]|[FfRr])(?<seqRunCountID>_.*)?\.fastq(?<zipOption>.gz)?
```
In the complete solution we will need to be able to handle correctly pairing files together even when they are mixed.

**Comment by ericenns** [comment]
@JeffreyThiessen I think your going a little too exhaustive on this set of examples. I.e. supporting files that end in `_001` after the pair indicator. We already have a specific illumina named file matcher that recognizes the pattern that illumina fastq files adhere to  (e.g. https://help.basespace.illumina.com/files-used-by-basespace/fastq-files).

For non illumina paired end files we should just match ones that end in commonly used paired end indicators e.g. the ones in your original comment but it should also allow `.fq` in addition to `.fastq`.

For edge cases, we could consider to add in the ability for the user to pair files together in the interface that were detected as being pair end.

**Comment by JeffreyThiessen** [comment]
@ericenns Yeah I think that's a good solution with allowing users to manually pair files if they don't match the default.

As for `_001`, even though Illumina says that files always end in `_001`, it's not always the case. If users need to do a top off run on an existing run, the files will have `_002` iirc. These extra run files are rare and usually only a few samples so having those be manually paired would likely solve those use cases too.
