### ISSUE TITLE
Samples - Clone Service

### ISSUE THREAD

**Issue by deepsidhu85** [phac-nml/irida-next#402]
## Summary
As a user I want to be able to clone data or a subset of data that has been shared with me, into my own project so that I can perform analyses and edit the data without affecting the original source data

## Acceptance Criteria
- `CloneService` which accepts `current_project`, `user`, `new_project_id`, `sample_ids` 
- The service will create new samples in the `destination` project by cloning the passed samples
- The following can be done by most likely re-using previously added services
    1. Clone metadata from the old samples into the new samples
    2. Create new attachments in the sample from existing attachments
- User must have at least a `Maintainer` role in both the `source` and `destination` project
- Project can only contain one copy of the same data (sample name, attachments in sample)
- User can delete the data (samples, attachment files) from their project that they duplicated from another project
- User can run analyses on data (samples -> attachment files)
- User can download data (files)

**Comment by ksierks** [comment]
Confirmed that the last 3 bullet points can be tested in the UI branch.
