### ISSUE TITLE
GraphQL: isPuid query

### ISSUE THREAD

**Issue by ericenns** [phac-nml/irida-next#615]
## Summary

As a User I would like to be able to query an id and determine if it matches the format of a PUID.

Related to `DFCT0010065`

## Acceptance Criteria
* Create a new `isPuid` query the adhere's to the following criteria
  * Accepts the following arguments:
    * `id` which is of type `ID`
  * Returns  a Boolean:
    * `true` when the `id` supplied matches the format of a `PersisentUniqueID` (refer to `valid_puid?` in `lib/irida/persistent_unique_id.rb`)
      * Possible `object_class` are `Sample`, `Attachment`, `Group`, and `Namespace::ProjectNamespace`
    * `false` if it doesn't match any known PUID types

**Comment by deepsidhu85** [comment]
Fixed in #625
