### ISSUE TITLE
Members: Add searching and sorting to table (ENHC0010037)

### ISSUE THREAD

**Issue by deepsidhu85** [phac-nml/irida-next#641]
## Summary

Currently, the members table for both groups and projects does not have sorting or searching capability. We want to update the table to add this functionality to allow the user to sort and search

## Acceptance Criteria

- Since the members listing pages are pretty much identical, convert these over to be a component which will be shared by both the project and groups member index templates
- Search functionality added ( searches username ~~and access level~~)
- Sort functionality added for all columns except `Access Granted` and `Actions`

Note: Take a look at the files within `app/components/samples` for an example of how this should work.

**Comment by ksierks** [comment]
After a conversation with Deep today, we've decided to drop searching by access level for now. 

For my future reference, we explored the following solutions:
1. convert database to use enums
2. use a dropdown to do access level searching/filtering
3. use a ransacker to do complete name lookup
4. use ransackable_scope
