### ISSUE TITLE
Group Settings Update

### ISSUE THREAD

**Issue by ericenns** [phac-nml/irida-next#75]
### Summary
Update the Group Settings page to separate updates to `path` and `parent` namespace into the `Advanced` section.

### Implementation Guide
* Remove `path` and `parent namespace` updates from `Name and description` section.
* Add `Change group URL` under `Advanced` section and only allow changing the `path`
  * Make POST request to group_path (normal update endpoint)
* Add `Transfer group` under `Advanced` section and allow user to select any group, subgroup, or personal namespace they have access to
  * Add `groups/transfer_service.rb` (can use `projects/transfer_service.rb` as an example).
  * Add `transfer` method to `groups_controller.rb` and call the `groups/transfer_service.rb`
  * Add `transfer` endpoint to `routes/groups.rb` using `PUT` method

**Comment by ksierks** [comment]
@ericenns @josh I have a small question. It looks like at one point the accordion was used to organise the group advanced settings. I also see that the card is being used in the [WIP: Project settings update](https://github.com/phac-nml/irida-next/pull/92/files#top) #92 PR. Do I continue to use the accordion or use the card for consistency? Thanks.

**Comment by ksierks** [comment]
Done.
