### ISSUE TITLE
Data Exports: Table Paging, Searching, and Sorting

### ISSUE THREAD

**Issue by ericenns** [phac-nml/irida-next#758]
## Summary

Currently the DataExports Index page loads all of the DataExports that a User has created, this means that the page will continue to take longer to respond as the User creates more and more DataExports.

## Acceptance Criteria
* As a User I would like to be able to search through the data exports table by ID or Name
* As a User I would like to be able to sort by the columns, with a default sort on the `updated_at` column so the latest export is always one the first page and the top of the list by default

**Comment by ksierks** [comment]
@ericenns I have some clarification questions.
- The table currently only displays the created_at and expires_at dates. Can the default sort be created_at?
- Should a limit component be displayed for the pagination?
- Should this PR include converting the table into a view components?
- Should the sorting and searching use turbo_streams?
Thank you.

**Comment by ericenns** [comment]
> @ericenns I have some clarification questions.
> 
> - The table currently only displays the created_at and expires_at dates. Can the default sort be created_at?
>
Yeah that works.
> - Should a limit component be displayed for the pagination?
> 
Yes, a limit component should be displayed.
> - Should this PR include converting the table into a view components?
> 
Yes, that is a good idea.
> - Should the sorting and searching use turbo_streams?
> 
No need to use turbo_streams or a separate endpoint for this one as it is a basic search.
> Thank you.
