### ISSUE TITLE
Project Settings Update

### ISSUE THREAD

**Issue by ericenns** [phac-nml/irida-next#76]
### Summary
Update the Project Settings page to separate updates to `path` and `parent` namespace into a new `Advanced` section.

### Implementation Guide
* [x] Remove `path` and `parent namespace` updates from `Name and description` section.
* [x] Add `Change path` under `Advanced` section and only allow changing the `path`
  * Make POST request to project_path (normal update endpoint)
* [x] Add `Transfer project` under `Advanced` section and allow user to select any group, subgroup, or personal namespace they have access to
  * Use `transfer` action with `PUT` request
* [x] Add `Delete project` under `Advanced` section
  * Use `destroy` action with `DELETE` request

**Comment by ksierks** [comment]
Done.
